trayDimensions={
	"2":{
		"Height":"12",
		"Top":{"Width":"105","Breadth":"105"},
		"Base":{"Width":"90","Breadth":"90"},
		"CompartmentList":{
			"Compartment":[
				{"CompartmentIndex":"1",
				"Height":"12",
				"Top":{"Width":"57.5","Breadth":"105"},
				"Base":{"Width":"57.5","Breadth":"105"}
				},
				{"CompartmentIndex":"2",
				"Height":"12",
				"Top":{"Width":"57.5","Breadth":"105"},
				"Base":{"Width":"57.5","Breadth":"105"}
				}
			]
		}
	},
	"16":{
		"Height":"200",
		"Top":{"Width":"105","Breadth":"105"},
		"Base":{"Width":"90","Breadth":"90"},
		"CompartmentList":{
			"Compartment":[
				{"CompartmentIndex":"1",
				"Height":"100",
				"Top":{"Width":"100","Breadth":"100"},
				"Base":{"Width":"100","Breadth":"100"}
				}
			]
		}
	},
	"1":{
		"Height":"12",
		"Top":{"Width":"105","Breadth":"155"},
		"Base":{"Width":"90","Breadth":"135"},
		"CompartmentList":{
			"Compartment":[
				{"CompartmentIndex":"1",
				"Height":"12",
				"Top":{"Width":"55","Breadth":"155"},
				"Base":{"Width":"50","Breadth":"135"}
				},
				{"CompartmentIndex":"2",
				"Height":"12",
				"Top":{"Width":"50","Breadth":"155"},
				"Base":{"Width":"40","Breadth":"135"}
				},
				{"CompartmentIndex":"3",
				"Height":"12",
				"Top":{"Width":"60","Breadth":"156"},
				"Base":{"Width":"46","Breadth":"136"}
				}
			]
		}
	}
}